version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
  web:
    build: ./project
    command: 'python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - './project:/app'
      - './public:/app/public'
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - db
