# Generated by Django 2.2.6 on 2019-10-22 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('rarity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='SkillBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('skill_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bass.SkillPoint')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('points_required', models.IntegerField()),
                ('skill_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='bass.SkillPoint')),
                ('tags', models.ManyToManyField(related_name='skills', to='bass.SkillTag')),
                ('weapon_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bass.WeaponClass')),
            ],
        ),
        migrations.CreateModel(
            name='Resistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bass.Element')),
            ],
        ),
        migrations.CreateModel(
            name='Armour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(0, 'Both'), (1, 'Male'), (2, 'Female')])),
                ('part', models.IntegerField(choices=[(0, 'Head'), (1, 'Torso'), (2, 'Arms'), (3, 'Waist'), (4, 'Legs')])),
                ('defence', models.IntegerField()),
                ('slots', models.IntegerField()),
                ('points', models.ManyToManyField(to='bass.SkillBonus')),
                ('resistances', models.ManyToManyField(to='bass.Resistance')),
                ('weapon_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bass.WeaponClass')),
            ],
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bass.Item')),
                ('slots', models.IntegerField()),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorations', to='bass.SkillBonus')),
                ('penalty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bass.SkillBonus')),
            ],
            bases=('bass.item',),
        ),
    ]
